import { Montserrat } from "next/font/google";
import MainWrapper from "@/app/mainlayout";
import { ProvideContext } from "./AuthContext";
import { ToastContainer } from "react-toastify";
import "@/app/globals.css";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserratSans.variable} antialiased`}>
        <ProvideContext>
          <MainWrapper>{children}</MainWrapper>
          <ToastContainer />
        </ProvideContext>
      </body>
    </html>
  );
}
