import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import { AppProvider } from "@/app/AppContext";
import { Jost } from "next/font/google";
import "./globals.css";

const jostSans = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jostSans.className} antialiased`}>
        <AppProvider>
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
